# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/mango/UE/UE5.1
GAMEPROJECTFILE =/home/mango/Documents/Unreal Projects/VRST/VRST.uproject

TARGETS = \
	VRST-Linux-DebugGame  \
	VRST-Linux-Shipping  \
	VRST \
	VRSTEditor-Linux-DebugGame  \
	VRSTEditor-Linux-Shipping  \
	VRSTEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend VRSTEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug VRSTEditor-Linux-Debug


VRST-Linux-DebugGame:
	 $(PROJECTBUILD) VRST Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

VRST-Linux-Shipping:
	 $(PROJECTBUILD) VRST Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

VRST:
	 $(PROJECTBUILD) VRST Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

VRSTEditor-Linux-DebugGame:
	 $(PROJECTBUILD) VRSTEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

VRSTEditor-Linux-Shipping:
	 $(PROJECTBUILD) VRSTEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

VRSTEditor:
	 $(PROJECTBUILD) VRSTEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
